Shop/ShopTechOnline/ShopTechOnline/Models/EF/SystemSetting.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace ShopTechOnline.Models.EF
{
    [Table("SystemSetting")]

    public class SystemSetting
    {
        [Key]
        [StringLength(50)]
        public string SettingKey { get; set; }

        [StringLength(4000)]
        public string SettingValue { get; set; }

        [StringLength(4000)]
        public string SettingDescription { get; set; }
    }
}

Shop/ShopTechOnline/ShopTechOnline/Areas/Admin/Controllers/SystemSettingsController.cs
using ShopTechOnline.Models;
using ShopTechOnline.Models.EF;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ShopTechOnline.Areas.Admin.Controllers
{
    // Cấu hình hệ thống

    public class SystemSettingsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        // GET: Admin/SystemSettings
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Partial_Setting()
        {
            return PartialView();
        }

        [HttpPost]
        public ActionResult AddSetting(SettingSystemViewModel req)
        {
            // kiểm tra checktitle
            SystemSetting set = null;
            var checkTitle = db.systemSettings.FirstOrDefault(x => x.SettingKey.Contains("SettingTitle"));
            if ( checkTitle == null)
            {
                set = new SystemSetting();
                set.SettingKey = "SettingTitle";
                set.SettingValue = req.SettingTitle;
                db.systemSettings.Add(set);
            }
            else
            {
                checkTitle.SettingValue = req.SettingTitle;
                db.Entry(checkTitle).State = System.Data.Entity.EntityState.Modified;
            }
            // kiểm tra checklogo
            var checkLogo = db.systemSettings.FirstOrDefault(x => x.SettingKey.Contains("SettingLogo"));
            if (checkLogo == null)
            {
                set = new SystemSetting();
                set.SettingKey = "SettingLogo";
                set.SettingValue = req.Settinglogo;
                db.systemSettings.Add(set);
            }
            else
            {
                checkLogo.SettingValue = req.Settinglogo;
                db.Entry(checkLogo).State = System.Data.Entity.EntityState.Modified;
            }
            // kiểm tra checkemail
            var checkEmail = db.systemSettings.FirstOrDefault(x => x.SettingKey.Contains("SettingEmail"));
            if (checkEmail == null)
            {
                set = new SystemSetting();
                set.SettingKey = "SettingEmail";
                set.SettingValue = req.SettingEmail;
                db.systemSettings.Add(set);
            }
            else
            {
                checkEmail.SettingValue = req.SettingEmail;
                db.Entry(checkEmail).State = System.Data.Entity.EntityState.Modified;
            }
            // kiểm tra checkhotline
            var checkHotline = db.systemSettings.FirstOrDefault(x => x.SettingKey.Contains("SettingHotline"));
            if (checkHotline == null)
            {
                set = new SystemSetting();
                set.SettingKey = "SettingHotline";
                set.SettingValue = req.SettingHotline;
                db.systemSettings.Add(set);
            }
            else
            {
                checkHotline.SettingValue = req.SettingHotline;
                db.Entry(checkHotline).State = System.Data.Entity.EntityState.Modified;
            }
            // kiểm tra Titleseo
            var Titleseo = db.systemSettings.FirstOrDefault(x => x.SettingKey.Contains("SettingTitleSeo"));
            if (Titleseo == null)
            {
                set = new SystemSetting();
                set.SettingKey = "SettingTitleSeo";
                set.SettingValue = req.SettingTitleSeo;
                db.systemSettings.Add(set);
            }
            else
            {
                Titleseo.SettingValue = req.SettingTitleSeo;
                db.Entry(Titleseo).State = System.Data.Entity.EntityState.Modified;
            }
            // kiểm tra DesSeo
            var DesSeo = db.systemSettings.FirstOrDefault(x => x.SettingKey.Contains("SettingDesSeo"));
            if (DesSeo == null)
            {
                set = new SystemSetting();
                set.SettingKey = "SettingDesSeo";
                set.SettingValue = req.SettingDesSeo;
                db.systemSettings.Add(set);
            }
            else
            {
                DesSeo.SettingValue = req.SettingDesSeo;
                db.Entry(DesSeo).State = System.Data.Entity.EntityState.Modified;
            }
            // kiểm tra KeySeo
            var KeySeo = db.systemSettings.FirstOrDefault(x => x.SettingKey.Contains("SettingKeySeo"));
            if (KeySeo == null)
            {
                set = new SystemSetting();
                set.SettingKey = "SettingKeySeo";
                set.SettingValue = req.SettingKeySeo;
                db.systemSettings.Add(set);
            }
            else
            {
                KeySeo.SettingValue = req.SettingKeySeo;
                db.Entry(KeySeo).State = System.Data.Entity.EntityState.Modified;
            }

            db.SaveChanges();
            return View("Partial_Setting");
        }
    }
}

Shop/ShopTechOnline/ShopTechOnline/Areas/Admin/Views/SystemSettings/Index.cshtml
@{
    ViewBag.Title = "Cấu hình hệ thống";
}

@section naviheader{
    <!-- Left navbar links -->
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="/admin" class="nav-link">Trang chủ</a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="/admin/" class="nav-link">@ViewBag.Title</a>
        </li>
    </ul>
}
<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>@ViewBag.Title</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="#">Trang chủ</a></li>
                    <li class="breadcrumb-item active">@ViewBag.Title</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

<!-- Main content -->
<section class="content">

    <!-- Default box -->
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">@ViewBag.Title</h3>

        </div>
        <div class="card-body">
            <div id="load_page"></div>
            @Html.Action("Partial_Setting", "SystemSettings")
        </div>
        <!-- /.card-body -->
        <div class="card-footer">

        </div>
        <!-- /.card-footer-->
    </div>
    <!-- /.card -->

</section>
<!-- /.content -->
@section scripts{
    <script>
        function BrowseServer(field) {
            var finder = new CKFinder();
            finder.selectActionFunction = function (fileUrl) {
                document.getElementById(field).value = fileUrl;
            };
            finder.popup();
        }
    </script>
    }

Shop/ShopTechOnline/ShopTechOnline/Areas/Admin/Views/SystemSettings/Partial_Setting.cshtml
@using ShopTechOnline.Models
@using (Ajax.BeginForm("AddSetting", "SystemSettings", new AjaxOptions
{
    OnBegin = "OnBegin",
    OnSuccess = "OnSuccess",
    OnFailure = "OnFailure"
}))
{
    <script>
        function OnBegin() {
            $('#load_page').html('Đang lưu...');
        }
        function OnSuccess(rs) {
            $('#load_page').html('');
        }
        function OnFailure(rs) {

        }
    </script>

    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    <div class="row">
        <div class="col-12">
            <div class="card">

                <div class="card-header p-2">
                    <ul class="nav nav-pills">
                        <li class="nav-item"><a class="nav-link active" href="#activity" data-toggle="tab">Thông tin chung</a></li>
                        <li class="nav-item"><a class="nav-link" href="#settingSeo" data-toggle="tab">SEO</a></li>
                    </ul>
                </div><!-- /.card-header -->

                <div class="card-body">
                    <div class="tab-content">
                        <div class="active tab-pane" id="activity">
                            <div class="form-group">
                                <label>Tiêu đề trang</label>
                                <input type="text" name="SettingTitle" class="form-control" value="@SettingHelper.GetValue("SettingTitle")" />
                            </div>
                            <div class="form-group">
                                <label>Logo</label>
                                <div class="input-group">
                                    <div class="custom-file">
                                        <input type="text" value="@SettingHelper.GetValue("SettingLogo")" name="SettingLogo" id="txtSettingLogo" class="form-control" />
                                    </div>
                                    <div class="input-group-append">
                                        <input type="button" value="Tải ảnh" onclick="BrowseServer('txtSettingLogo');" />
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <label>Hotline</label>
                                <input type="text" value="@SettingHelper.GetValue("SettingHotline")" name="SettingHotline" class="form-control" />
                            </div>
                            <div class="form-group">
                                <label>Email</label>
                                <input type="text" value="@SettingHelper.GetValue("SettingEmail")" name="SettingEmail" class="form-control" />
                            </div>

                        </div>
                        <div class="tab-pane" id="settingSeo">
                            <div class="form-group">
                                <label>Tiêu đề seo</label>
                                <input type="text" value="@SettingHelper.GetValue("SettingTitleSeo")" name="SettingTitleSeo" class="form-control" />
                            </div>
                            <div class="form-group">
                                <label>Mô tả seo</label>
                                <textarea name="SettingDesSeo" class="form-control" rows="3">@SettingHelper.GetValue("SettingDesSeo")</textarea>
                            </div>
                            <div class="form-group">
                                <label>Từ khóa seo</label>
                                <textarea name="SettingKeySeo" class="form-control" rows="3">@SettingHelper.GetValue("SettingKeySeo")</textarea>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="col-12">
            <div>
                <button type="submit" class="btn btn-success">Lưu</button>
            </div>
        </div>

    </div>
}